
volumes:
  caddy_data:
  caddy_config:

services:
  n8n:
    environment:
      - WEBHOOK_URL
  
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    networks: ['demo']
    ports:
      - 80:80
      - 1443:443
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - WEBHOOK_URL
    env_file:
      - .env
